name: 同步 Solitude 主题

on:
  schedule:
    - cron: '0 2 * * 0'  # 每周日北京时间上午 10:00 运行（UTC 时间 2:00）
  workflow_dispatch:  # 允许手动触发

jobs:
  sync-theme:
    runs-on: ubuntu-latest

    steps:
      - name: 检出 blog-solitude 仓库
        uses: actions/checkout@v3
        with:
          repository: yutianqq/blog-solitude
          token: ${{ secrets.GITHUB_TOKEN }}
          path: blog-solitude

      - name: 检出 hexo-theme-solitude 仓库
        uses: actions/checkout@v3
        with:
          repository: everfu/hexo-theme-solitude
          path: hexo-theme-solitude

      - name: 检查是否有更新
        id: check-update
        run: |
          cd hexo-theme-solitude
          REMOTE_COMMIT=$(git rev-parse HEAD)
          cd ../blog-solitude/themes/solitude
          LOCAL_COMMIT=$(git rev-parse HEAD 2>/dev/null || echo "无本地提交记录")
          if [ "$REMOTE_COMMIT" != "$LOCAL_COMMIT" ]; then
            echo "检测到 hexo-theme-solitude 有更新，将同步文件。"
            echo "has_update=true" >> $GITHUB_OUTPUT
          else
            echo "hexo-theme-solitude 无更新，无需同步。"
            echo "has_update=false" >> $GITHUB_OUTPUT
          fi

      - name: 同步主题文件
        if: steps.check-update.outputs.has_update == 'true'
        run: |
          mkdir -p blog-solitude/themes/solitude
          cp -r hexo-theme-solitude/* blog-solitude/themes/solitude/
          echo "已同步 hexo-theme-solitude 最新文件到 blog-solitude/themes/solitude 目录。"

      - name: 提交并推送更改
        if: steps.check-update.outputs.has_update == 'true'
        run: |
          cd blog-solitude
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add themes/solitude
          git commit -m "同步 everfu/hexo-theme-solitude 主题：$(date -d '+8 hours' +'%Y-%m-%d')"
          git push
          echo "已提交并推送更改至 blog-solitude 仓库。"
